# Generated by Django 5.0 on 2024-06-08 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('req_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_recived', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('to', 'req_from')},
            },
        ),
    ]
