# Generated by Django 5.0 on 2024-06-08 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='req_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
